# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Quick Adaptive Ternary Segmentation, timing in C++
#'
#' @param d0 Smallest search interval
#' @param n_seeds Number of seeds for the optimistic search
#' @param rotate Indicates whether or not the gain functions have to be rotated
#' @param n_rep Number of repetition (for timing)
#' @param n Length of the sequence
#' @param m Cardinality of the state space
#' @param logPi Log-initial distribution
#' @param qq Log-transition probabilities
#' @param GG Cumulative log-emission densities
#' @param SS Initial partition
#' @param UU Length of the initial partition
#'
#' @keywords internal
QATS_timer_cpp <- function(d0, n_seeds, rotate, n_rep, n, m, logPi, qq, GG, SS, UU) {
    .Call(`_QATS_QATS_timer_cpp`, d0, n_seeds, rotate, n_rep, n, m, logPi, qq, GG, SS, UU)
}

#' Viterbi decoder, timing in C++
#'
#' @param n Length of the observation sequence
#' @param n_rep Number of repetition (for timing)
#' @param m Cardinality of the state space
#' @param logPi Initial log-distribution
#' @param qq Log-transition matrix
#' @param g_mseq Log-densities of the emission distributions
#'
#' @return Estimated sequence
#' @keywords internal
Viterbi_timer_cpp <- function(n_rep, n, m, logPi, qq, g_mseq) {
    .Call(`_QATS_Viterbi_timer_cpp`, n_rep, n, m, logPi, qq, g_mseq)
}

#' Viterbi decoder
#'
#' @param xx Pre-declared sequence to be updated
#' @param n Length of the observation sequence
#' @param m Cardinality of the state space
#' @param logPi Initial log-distribution
#' @param qq Log-transition matrix
#' @param g_mseq Log-densities of the emission distributions
#'
#' @return Estimated sequence
#' @keywords internal
Viterbi_cpp <- function(xx, zeta, rho, n, m, logPi, qq, g_mseq) {
    invisible(.Call(`_QATS_Viterbi_cpp`, xx, zeta, rho, n, m, logPi, qq, g_mseq))
}

#' G-classifier
#'
#' @param C1 Constant 1
#' @param C2 Constant 2
#' @param C3 Constant 3
#' @param C4 Constant 4
#' @param n Length of the observation sequence
#' @param m Cardinality of the state space
#' @param Pi Initial distribution
#' @param logPi Initial log-distribution
#' @param pp Transition matrix
#' @param qq Log-transition matrix
#' @param f_mseq Densities of the emission distributions
#' @param g_mseq Log-densities of the emission distributions
#'
#' @return Estimated sequence
#' @keywords internal
G_classifier_cpp <- function(C1, C2, C3, C4, n, m, Pi, logPi, pp, qq, f_mseq, g_mseq) {
    .Call(`_QATS_G_classifier_cpp`, C1, C2, C3, C4, n, m, Pi, logPi, pp, qq, f_mseq, g_mseq)
}

#' K-segmentation
#'
#' @param K_max Maximum number of constant pieces
#' @param n Length of the observation sequence
#' @param m Cardinality of the state space
#' @param logPi Initial log-distribution
#' @param qq Log-transition matrix
#' @param g_mseq Log-densities of the emission distributions
#'
#' @return Estimated sequences
#' @keywords internal
K_segmentation_cpp <- function(K_max, n, m, logPi, qq, g_mseq) {
    .Call(`_QATS_K_segmentation_cpp`, K_max, n, m, logPi, qq, g_mseq)
}

#' @keywords internal
H1_dbl_cpp <- function(l, r, x0, m, logPi, qq, GG) {
    .Call(`_QATS_H1_dbl_cpp`, l, r, x0, m, logPi, qq, GG)
}

#' @keywords internal
H2_vec_cpp <- function(l, r, x0, m, logPi, qq, GG) {
    .Call(`_QATS_H2_vec_cpp`, l, r, x0, m, logPi, qq, GG)
}

#' @keywords internal
H3_mat_cpp <- function(l, r, x0, m, logPi, qq, GG) {
    .Call(`_QATS_H3_mat_cpp`, l, r, x0, m, logPi, qq, GG)
}

#' @keywords internal
sample_norm_HMM_export_cpp <- function(n, m, Pi, pp, sigma) {
    .Call(`_QATS_sample_norm_HMM_export_cpp`, n, m, Pi, pp, sigma)
}

#' Generate a sample and estimate paths using QATS and different seeds
#'
#' @param n Length of the sequence
#' @param m Cardinality of the state space
#' @param Pi Initial state distribution
#' @param pp Transition matrix
#' @param sigma Standard deviation of the normal emission distribution
#' @param d0 Smallest search interval
#' @param n_seeds Number of seeds for the optimistic search
#' @param rotate Indicates whether or not the gain functions have to be rotated
#' @param n_rep Number of repetition (for timing)
#' @param n_sim Number of simulations
#'
#' @return A matrix containing estimation times and errors for QATS
#'
#' @export
QATS_nseeds_norm <- function(n, m, Pi, pp, sigma, d0, n_seeds, rotate, n_rep, n_sim) {
    .Call(`_QATS_QATS_nseeds_norm_cpp`, n, m, Pi, pp, sigma, d0, n_seeds, rotate, n_rep, n_sim)
}

#' Generate a sample and estimate paths using QATS and Viterbi
#'
#' @param n Length of the sequence
#' @param m Cardinality of the state space
#' @param Pi Initial state distribution
#' @param pp Transition matrix
#' @param sigma Standard deviation of the normal emission distribution
#' @param d0 Smallest search interval
#' @param n_seeds Number of seeds for the optimistic search
#' @param rotate Indicates whether or not the gain functions have to be rotated
#' @param n_rep Number of repetition (for timing)
#' @param n_sim Number of simulations
#'
#' @return A list containing estimation times and errors for both QATS and
#' Viterbi
#'
#' @export
QATS_vs_Viterbi_norm <- function(n, m, Pi, pp, sigma, d0, n_seeds, rotate, n_rep, n_sim) {
    .Call(`_QATS_QATS_vs_Viterbi_norm_cpp`, n, m, Pi, pp, sigma, d0, n_seeds, rotate, n_rep, n_sim)
}

